### ISSUE TITLE
Cannot install - node red cannot read property 'nodes' of null

### ISSUE THREAD

**Issue by LarsIvar** [simplepush/node-red-contrib-simplepush#2]
Integration with node-RED Failed to install via user settings -> palette: 

node-red-contrip-simplepush  
cannot read property 'nodes' of null.

**Comment by simplepush** [comment]
Hey @LarsIvar,

which version of Node-RED are you using?

**Comment by LarsIvar** [comment]
Hi.

I’m using Node-RED v 1.2.3

Thank you for looking into my issue!

**Comment by simplepush** [comment]
`node-red-contrib-simplepush` requires a Node-RED version >=1.2.9.
Out of curiosity, can you update your Node-RED or is there a reason why you need to stick with 1.2.3?

**Comment by LarsIvar** [comment]
Thank you. Upgrading node-RED and node.js solved it!
